### ISSUE TITLE
python 运行问题

### ISSUE THREAD

**Issue by liyown** [WECENG/ticket-purchase#13]
![image](https://github.com/WECENG/ticket-purchase/assets/55525531/bec4d77c-5081-4086-b1fd-4fd2603a504f)

**Comment by liyown** [comment]
这个是什么问题

**Comment by WECENG** [comment]
appium server 没有启动吧

**Comment by liyown** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/55525531/2f0728bf-9c7e-4559-b1be-eeaa185e0228)
这样是启动成功了吗

**Comment by liyown** [comment]
然后会显示如下问题：
(damai) D:\github\ticket-purchase\damai_appium>python damai_app.py
Traceback (most recent call last):
  File "D:\github\ticket-purchase\damai_appium\damai_app.py", line 43, in <module>                                                       
    driver = webdriver.Remote(config.server_url, options=device_app_info)                                                                
  File "D:\APPs\Professionalsoftware\anaconda\envs\damai\lib\site-packages\appium\webdriver\webdriver.py", line 229, in __init__         
    super().__init__(                                                                                                                    
  File "D:\APPs\Professionalsoftware\anaconda\envs\damai\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)                                                                                                     
  File "D:\APPs\Professionalsoftware\anaconda\envs\damai\lib\site-packages\appium\webdriver\webdriver.py", line 318, in start_session    
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)                                                                         
  File "D:\APPs\Professionalsoftware\anaconda\envs\damai\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "D:\APPs\Professionalsoftware\anaconda\envs\damai\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not sup
ported by the mapped resource

**Comment by liyown** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/55525531/0ef4d4c6-cc4b-4acc-b736-07d0ae9a540e)

**Comment by WECENG** [comment]
连同一个无线网络

**Comment by liyown** [comment]
模拟器好像不能登录大麦，我试了联想模拟器和雷电模拟器，都是无法通过验证

**Comment by liyown** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/55525531/cfdd2328-f09d-487f-b290-99ff1f1768ef)
一路问题解决过来，最终卡在日期无法选择这里，我试过不加0和加0

**Comment by WECENG** [comment]
修复好了https://github.com/WECENG/ticket-purchase/commit/86d726bbded4126267cab90b7ae30e890615d701
