### ISSUE TITLE
Mac电脑的

### ISSUE THREAD

**Issue by xm0034** [WECENG/ticket-purchase#64]
有按照指示改了config.json中的信息，下载了谷歌浏览器，有下载驱动但是不知道要怎么匹配操作，直接运用的脚本现在的报错，可以帮忙看看不
xumiao@192 ticket-purchase-master % python3 "/Users/xumiao/Desktop/ticket-purchase-master/damai/damai.py"
Traceback (most recent call last):
  File "/Users/xumiao/Desktop/ticket-purchase-master/damai/damai.py", line 47, in <module>
    grab()
  File "/Users/xumiao/Desktop/ticket-purchase-master/damai/damai.py", line 31, in grab
    config = load_config()
             ^^^^^^^^^^^^^
  File "/Users/xumiao/Desktop/ticket-purchase-master/damai/damai.py", line 16, in load_config
    with open('config.json', 'r', encoding='utf-8') as config_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by QuasarNe** [comment]
提示就是找不到config.json文件，你的config是不是不在原目录下或者你改了名字？
