### ISSUE TITLE
运行python damai_app_qiang.py时报错

### ISSUE THREAD

**Issue by 1106948097** [WECENG/ticket-purchase#65]
<img width="1276" alt="Snipaste_2024-11-04_19-15-19" src="https://github.com/user-attachments/assets/9889a1fd-edee-4f5c-bc8b-c1b0a9a6b38f">

C:\Users\ca\Downloads\damai_grab_votes-main\damai_appium>python damai_app_qiang.py
Traceback (most recent call last):
  File "C:\Users\ca\Downloads\damai_grab_votes-main\damai_appium\damai_app_qiang.py", line 53, in <module>
    driver = webdriver.Remote(config.server_url, options=device_app_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\python\Lib\site-packages\appium\webdriver\webdriver.py", line 226, in __init__
    super().__init__(
  File "D:\software\python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "D:\software\python\Lib\site-packages\appium\webdriver\webdriver.py", line 316, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "D:\software\python\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to find an active device or emulator with OS 12. The following are available: OZQ8T4XKFYTCJNHQ (14)
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to find an active device or emulator with OS 12. The following are available: OZQ8T4XKFYTCJNHQ (14)
    at getResponseForW3CError (D:\software\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1145:9)
    at asyncHandler (D:\software\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:485:57)
    
    
    
    大佬们能帮我看看这是什么报错么

**Comment by 1106948097** [comment]
我看这个报错是说我的设备操作系统是os14,那我应该怎么办,来模拟os12的设备呀

**Comment by fj0203** [comment]
> 我看这个报错是说我的设备作系统是os14，那我应该怎么办，来模拟os12的设备呀

设备版本问题
